
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keys
spec:
  provider: azure
  secretObjects:                             
  - data:
    - key: postgres-url                          
      objectName: postgres-url     
    - key: postgres-user                          
      objectName: postgres-user
    - key: postgres-pass                          
      objectName: postgres-pass                      
    secretName: dbsecret                    
    type: Opaque  
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "36411b0e-1fbf-4890-86a7-361bbee5b755"
    keyvaultName: "andy-cert-keyvault"
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: postgres-url
          objectType: secret                       # object types: secret, key or cert
          objectVersion: ""                     # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: postgres-user
          objectType: secret
          objectVersion: ""
        - |
          objectName: postgres-pass
          objectType: secret
          objectVersion: "" 
    tenantId: "49a64d5c-aa61-4cae-8b52-7b4c8771e050"

